# TODO(billy): this workflow has not been re-named from `acceptance` because
# Visual Snapshots compares against artifacts from the same workflow name (on main branch)
# We should rename this when we have a more finalized naming scheme.
#
# Also note that this name *MUST* match the filename because GHA
# only provides the workflow name (https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables)
# and GH APIs only support querying by workflow *FILENAME* (https://developer.github.com/v3/actions/workflows/#get-a-workflow)
name: acceptance
on:
  push:
    branches:
      - master
      - releases/**
  pull_request:

jobs:
  ensure_docker:
    name: ensure docker image
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    steps:
      - name: Checkout sentry
        uses: actions/checkout@v2

      - name: Install gcloud utils
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          export_default_credentials: true
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Ensure docker image
        uses: ./.github/actions/ensure-docker

  frontend:
    name: frontend tests
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    needs: [ensure_docker]

    env:
      VISUAL_HTML_ENABLE: 1

    steps:
      - name: Checkout sentry
        uses: actions/checkout@v2
        with:
          # Avoid codecov error message related to SHA resolution:
          # https://github.com/codecov/codecov-bash/blob/7100762afbc822b91806a6574658129fe0d23a7d/codecov#L891
          fetch-depth: '2'

      - name: Install gcloud utils
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          export_default_credentials: true
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Setup Sentry
        uses: ./.github/actions/setup-sentry-docker
        with:
          devservices: false

      - name: Run tests
        run: |
          docker exec sentry-test bin/test-utils/run_tests make ci-test-js

      - name: Create Images from HTML
        uses: getsentry/action-html-to-image@main
        with:
          base-path: .artifacts/visual-snapshots/jest
          css-path: ${{ github.workspace }}/dist/sentry.css

      - name: Save snapshots
        if: always()
        uses: getsentry/action-visual-snapshot@v2
        with:
          save-only: true
          snapshot-path: .artifacts/visual-snapshots

      - name: Handle artifacts
        uses: ./.github/actions/artifacts

  acceptance:
    name: acceptance
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    needs: [ensure_docker]

    strategy:
      matrix:
        instance: [0, 1, 2, 3]

    env:
      VISUAL_SNAPSHOT_ENABLE: 1
      TEST_GROUP_STRATEGY: roundrobin

    steps:
      - name: Checkout sentry
        uses: actions/checkout@v2

      - name: Install gcloud utils
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          export_default_credentials: true
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Setup Sentry
        uses: ./.github/actions/setup-sentry-docker
        with:
          snuba: true

      - name: Run tests
        id: test
        run: |
          mkdir -p .artifacts/visual-snapshots/acceptance
          mkdir -p .artifacts/visual-snapshots/acceptance-mobile
          mkdir -p .artifacts/visual-snapshots/acceptance-tooltips
          docker exec -e TEST_GROUP_STRATEGY=individual sentry-test bin/test-utils/run_tests make ci-test-acceptance

      - name: Save artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: acceptance
          path: .artifacts

      - name: Save snapshots
        if: always()
        uses: getsentry/action-visual-snapshot@v2
        with:
          save-only: true
          snapshot-path: .artifacts/visual-snapshots

      - name: Handle artifacts
        uses: ./.github/actions/artifacts
